export const GET_ALL_USER_DATA_REQUEST = "GET_ALL_USER_DATA_REQUEST";
export const GET_ALL_USER_DATA_SUCCESS = "GET_ALL_USER_DATA_SUCCESS";
export const GET_ALL_USER_DATA_FAILURE = "GET_ALL_USER_DATA_FAILURE";


export const POST_ALL_USER_DATA_REQUEST = "POST_ALL_USER_DATA_REQUEST";
export const POST_ALL_USER_DATA_SUCCESS = "POST_ALL_USER_DATA_SUCCESS";
export const POST_ALL_USER_DATA_FAILURE = "POST_ALL_USER_DATA_FAILURE";



export const PATCH_ALL_USER_DATA_REQUEST = "PATCH_ALL_USER_DATA_REQUEST";
export const PATCH_ALL_USER_DATA_SUCCESS = "PATCH_ALL_USER_DATA_SUCCESS";
export const PATCH_ALL_USER_DATA_FAILURE = "PATCH_ALL_USER_DATA_FAILURE";


export const DELETE_ALL_USER_DATA_REQUEST = "DELETE_ALL_USER_DATA_REQUEST";
export const DELETE_ALL_USER_DATA_SUCCESS = "DELETE_ALL_USER_DATA_SUCCESS";
export const DELETE_ALL_USER_DATA_FAILURE = "DELETE_ALL_USER_DATA_FAILURE";


export const GET_SINGLE_USER_DATA_REQUEST = "GET_SINGLE_USER_DATA_REQUEST";
export const GET_SINGLE_USER_DATA_SUCCESS = "GET_SINGLE_USER_DATA_SUCCESS";
export const GET_SINGLE_USER_DATA_FAILURE = "GET_SINGLE_USER_DATA_FAILURE";